<#
.Publish a self-contained-on-Windows delivery folder: Host + Worker + runtime config, without
any vendor КОМПАС binary. The second property is as important as the first: the interop is
referenced at build time only, and scripts/inspect-package.ps1 verifies nothing leaked.

Usage:  .\scripts\publish.ps1 [-Configuration Release] [-OutDir artifacts\publish]
#>
param(
    [string]$Configuration = "Release",
    [string]$OutDir = "artifacts\publish",
    [string]$KompasRoot = "D:\Programs\KOMPAS-3Dv24"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$full = Join-Path $root $OutDir

# ORDER AND -p:Platform ARE BOTH LOAD-BEARING — measured 18.09.2026, when this script could not
# publish a delivery at all.
#
#   1. -p:Platform=x64 is mandatory. Publishing a PROJECT (unlike `dotnet build KompasMcp.sln`) does
#      not consult the solution's configuration map, so $(Platform) stays AnyCPU. The Host's
#      CopyWorkerNextToHost target looks for the Worker under bin\$(Platform)\$(Configuration)\...,
#      i.e. bin\AnyCPU\Release\net10.0-windows, which no build of this solution ever writes
#      (KompasMcp.sln defines x64 only). The Host then failed with "KompasMcp.Worker output not
#      found at bin\AnyCPU\Release\net10.0-windows" and the delivery was never produced.
#   2. The Worker goes FIRST. That same target is a hard Error when the Worker output is absent, so
#      publishing the Host into an empty tree fails on a clean checkout. The guard is right — a
#      Host without its Worker is a delivery that dies at kompas_health — so the script satisfies it
#      rather than bypassing it.
foreach ($project in @("src\KompasMcp.Worker", "src\KompasMcp.Host")) {
    $target = Join-Path $root ($project -replace "\\", "/")
    Write-Host "publish $project"
    dotnet publish $target `
        -c $Configuration `
        -r win-x64 `
        -p:Platform=x64 `
        --self-contained false `
        -p:PublishSingleFile=false `
        -p:KompasRoot=$KompasRoot `
        -o $full
    if ($LASTEXITCODE -ne 0) { throw "publish failed for $project" }
}

# Config template travels with the binaries: an operator must be able to check the contract without
# a compiler. Only TEMPLATES ship. config\*.local.json holds the absolute paths of the machine that
# ran the build — shipping it would hand the customer foreign roots (its own models become
# unreachable, and the build workstation's layout leaks into a delivery). So the copy is filtered by
# name, and inspect-package.ps1 asserts the exclusion afterwards rather than trusting this filter.
$configDir = Join-Path $root "config"
$configOut = Join-Path $full "config"
New-Item -ItemType Directory -Force -Path $configOut | Out-Null
$templates = @(Get-ChildItem -Path $configDir -Filter "*.example.json" -File)
if ($templates.Count -eq 0) { throw "в $configDir нет шаблона *.example.json — поставка осталась бы без конфигурации" }
foreach ($template in $templates) {
    Copy-Item $template.FullName -Destination $configOut -Force
}

# Schemas are generated by the PUBLISHED binary, never copied from a build output folder. The line
# that used to sit here copied src\KompasMcp.Host\bin\x64\$Configuration\schemas, and that folder is
# written by whichever build ran last — so a delivery could carry the contract of a binary it does
# not contain. Asking the shipped Host is also the only way to prove the shipped template is
# loadable: --config is parsed before --emit-schemas is handled, so a template the Host cannot read
# fails HERE with rc=64 instead of failing on the customer's machine.
$publishedHost = Join-Path $full "KompasMcp.Host.exe"
& $publishedHost --config (Join-Path $configOut $templates[0].Name) --emit-schemas (Join-Path $full "schemas")
if ($LASTEXITCODE -ne 0) {
    throw "опубликованный Host не принял шаблон конфигурации или не выдал схемы (rc=$LASTEXITCODE)"
}

Write-Host "`nГотово: $full"
& (Join-Path $root "scripts\inspect-package.ps1") -Path $full
